name: uzbek_crypto
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.2.0
  firebase_database: ^11.1.0
  firebase_storage: ^12.2.0
  firebase_app_check: ^0.3.1+1

  cloud_firestore: ^5.4.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  http: ^0.13.5
  pinenacl: ^0.6.0
  darttonconnect: ^1.0.3
  url_launcher: ^6.3.0
  walletconnect_qrcode_modal_dart: ^0.4.3
  animations: ^2.0.11
  flutter_hooks: ^0.20.5
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  google_fonts: ^4.0.4
  tonutils: ^0.5.7
  ton_dart: ^0.1.0
  fl_chart: ^0.69.0
  convert: ^3.1.1
  wallet_connect: ^1.0.4
  lottie: ^3.1.2
  mask_text_input_formatter: ^2.9.0
  shared_preferences: ^2.3.2
  firebase_messaging: ^15.1.0
  firebase_analytics: ^11.3.0
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  easy_localization: ^3.0.7
  animate_do: ^3.3.4
  candlesticks: ^2.1.0
  carousel_slider: ^5.0.0
  intl_phone_number_input: ^0.7.4







dependency_overrides:
  http: ^0.13.5
  pinenacl: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_foreground.png"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/json/
    - assets/images/logo.png
    - assets/animations/
    - assets/translations/
    - assets/crypto/
    - assets/crypto/usdt.png
    - assets/banner/
