// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjf5nl7MPcgoaJ0-AwkUSz5txeL-PczXU',
    appId: '1:533618721067:web:9377bf139bfd61c185056e',
    messagingSenderId: '533618721067',
    projectId: 'finance-uz',
    authDomain: 'finance-uz.firebaseapp.com',
    databaseURL: 'https://finance-uz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'finance-uz.appspot.com',
    measurementId: 'G-7CVD192928',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAd8C5co5FbUaKGjA5iE0UjOgFZnKoF8g',
    appId: '1:533618721067:android:49ee794ba663a92c85056e',
    messagingSenderId: '533618721067',
    projectId: 'finance-uz',
    databaseURL: 'https://finance-uz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'finance-uz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCrMjxeJzz5OjfxeCJbfeR4GHDmzExEvw',
    appId: '1:533618721067:ios:a834da5e3791c12785056e',
    messagingSenderId: '533618721067',
    projectId: 'finance-uz',
    databaseURL: 'https://finance-uz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'finance-uz.appspot.com',
    iosBundleId: 'uz.buxoriy.uzbekcrypto.uzbekCrypto',
  );
}
