name: Dart (Flutter)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Flutter SDK ni o'rnatish
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'  # Yoki kerakli Flutter versiyasini ko'rsating

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
